version: "3"
services:

    hadoop:
      build: .
      image: hadoopyarnalone:3.2.0
      container_name: hadoop
      hostname: hadoop
      env_file:
        - .env
      ports:
        
        - 50010 
        - 50020 
        - 50070
    #    - 50075:50075
    #    - 50090:50090
        - 19888:19888
        - 8030:8030
        - 8031:8031
        - 8032:8032
        - 8033:8033
        - 8040:8040
        - 8042:8042
        - 9870:9870
        - 8088:8088
      #  - 49707:49707
        - 2122:2122
        - 22
      volumes: 
        - ../../:/home/hadoop
      
  
